### ISSUE TITLE
Closing print windows do not remove print area on map

### ISSUE THREAD

**Issue by yjacolin** [camptocamp/cgxp#985] opened 2015-08-07 08:14 UTC
The title is just a way to see the problem but there are others artefacts. 

When you close the print windows (not using the "close" button but the X icon in the top right of the window), the print area and form in the print window are not removed.

Thus, if you activate the print window again, the form and the print area are added once more. You can add as many as you want.

X icon should act as the "close" button.

**Comment by sbrunner** [comment] 2015-08-07 08:36
Duplicate of #975

**Closed by sbrunner** 2015-08-07 08:36 UTC
Labels: Bug
